#ifndef _INCLUDE_CFG_PROGIF_H_
#define _INCLUDE_CFG_PROGIF_H_

/*
 * Do not edit! Automatically generated on Thu Feb  4 13:47:09 2016
 */

#ifndef AVRTARGET_PAGESIZE
#define AVRTARGET_PAGESIZE 128
#endif

#ifndef AVRTARGET_CHIPERASE_TIMEOUT
#define AVRTARGET_CHIPERASE_TIMEOUT 200
#endif

#ifndef AVRTARGET_PAGEWRITE_TIMEOUT
#define AVRTARGET_PAGEWRITE_TIMEOUT 10
#endif

#ifndef AVRTARGET_SPI_MODE
#define AVRTARGET_SPI_MODE 0
#endif

#ifndef AVRTARGET_SPI_RATE
#define AVRTARGET_SPI_RATE 100000
#endif


#endif
